/**
 * ds-coverage — Example configuration
 *
 * This file is auto-generated by `npx ds-coverage init`.
 * You can also copy it manually and customize it.
 *
 * Run the interactive wizard: `npx ds-coverage init`
 * Or create this file manually and run: `npx ds-coverage init --no-interactive`
 *
 * All values below are examples — customize patterns to match YOUR design system.
 * @type {import('ds-coverage/config').DsCoverageConfig}
 */
export default {
  // ─── What to scan ────────────────────────────────────────
  scanDir: "src",
  extensions: [".tsx", ".jsx", ".ts", ".js"],
  exclude: [
    "node_modules/",
    "dist/",
    "build/",
    "test/",
    "__tests__/",
    ".test.",
    ".spec.",
    "stories/",
    ".storybook/",
  ],

  // ─── Violation categories ────────────────────────────────
  //
  // Each category defines a regex pattern to detect hardcoded values.
  // Customize these patterns to match YOUR CSS methodology:
  //
  // Tailwind:     "bg-gray-500", "text-sm", "rounded-lg"
  // CSS Modules:  "#ff0000", "font-size: 14px"
  // CSS-in-JS:    "color: '#ff0000'", "fontSize: 14"
  // Vanilla CSS:  "#ff0000", "font-size: 14px"
  //
  violations: {
    // Example: Tailwind hardcoded colors
    // colors: {
    //   enabled: true,
    //   label: "Couleurs",
    //   icon: "🎨",
    //   color: "oklch(0.637 0.237 25.331)",
    //   pattern: "(?:bg|text|border|ring)-(?:gray|red|blue|green)-\\d+",
    // },

    // Example: CSS hardcoded colors
    // colors: {
    //   enabled: true,
    //   label: "Couleurs",
    //   icon: "🎨",
    //   color: "oklch(0.637 0.237 25.331)",
    //   pattern: "#[0-9a-fA-F]{3,8}\\b|\\brgba?\\s*\\(|\\bhsla?\\s*\\(",
    // },

    // Example: Typography
    // typography: {
    //   enabled: true,
    //   label: "Typographie",
    //   icon: "🔤",
    //   color: "oklch(0.723 0.22 70.08)",
    //   pattern: "font-size\\s*:\\s*\\d+px",
    //   deduplicateByLine: true,
    // },
  },

  // ─── Migration flags ─────────────────────────────────────
  flags: {
    migrateSimple: "@ds-migrate:\\s*simple",
    migrateComplex: "@ds-migrate:\\s*complex",
    todo: "@ds-todo",
  },

  // ─── Component API analysis ──────────────────────────────
  componentAnalysis: {
    enabled: true,
    directories: ["components/ui/"],
    primaryDirectory: "components/ui/",
    legacyDirectories: [],
    api: {
      requireCVA: false,
      requireRadix: false,
      expectedProps: ["variant", "size"],
      forbiddenProps: [],
      expectedSizes: ["small", "medium", "large"],
      forbiddenSizes: [],
      legacyVariantValues: [],
    },
    scoring: {
      usesCVA: 0,
      correctNaming: 35,
      correctSizes: 25,
      hasClassName: 15,
      usesCompoundVariants: 0,
      hasAsChild: 0,
      usesRadix: 0,
    },
  },

  // ─── Roadmap phases ──────────────────────────────────────
  roadmap: {
    enabled: true,
    maxFilesPerPhase: 30,
    quickWinThreshold: 3,
    phases: [
      {
        id: "resolve-flags",
        title: "Resolve migration flags",
        description: "Files annotated with @ds-migrate from previous reviews.",
        businessCase: "Highest ROI — zero discovery cost, just execution.",
        filter: { type: "flags" },
      },
      {
        id: "quick-wins",
        title: "Quick wins — 1-3 violations",
        description: "Files that can be fully migrated with minimal effort.",
        businessCase: "Best coverage improvement per hour.",
        filter: { type: "quickWins" },
      },
    ],
  },

  // ─── Component Migration Plan ───────────────────────────
  //
  // Define component mappings when migrating between libraries.
  // Each mapping declares source → target with complexity and guidelines.
  //
  migration: {
    enabled: false, // set to true to enable the Migration Plan tab
    targetDS: "shadcn/ui", // name of the target design system
    mappings: [
      // Example mappings:
      // {
      //   source: "Button",
      //   sourceImportPattern: "@company/old-ui",
      //   target: "Button",
      //   targetImportPath: "@/components/ui/button",
      //   complexity: "simple",
      //   guidelines: "1. Update import path\n2. Rename 'intent' prop to 'variant'\n3. Remove 'isLoading' — use 'disabled' + spinner icon instead",
      //   propMapping: "intent → variant, isLoading → disabled",
      //   effort: "~15min",
      // },
      // {
      //   source: "Modal",
      //   sourceImportPattern: "@company/old-ui",
      //   target: "Dialog",
      //   targetImportPath: "@/components/ui/dialog",
      //   complexity: "moderate",
      //   guidelines: "1. Replace <Modal> with <Dialog> + <DialogContent>\n2. Move title to <DialogHeader><DialogTitle>\n3. Adapt onClose to Dialog's open/onOpenChange pattern",
      //   propMapping: "isOpen → open, onClose → onOpenChange, title → DialogTitle children",
      //   breakingChanges: [
      //     "Modal used imperative open/close — Dialog uses declarative open state",
      //     "Footer slot replaced by DialogFooter component",
      //   ],
      //   effort: "~1h",
      // },
      // {
      //   source: "DataTable",
      //   sourceImportPattern: "@company/old-ui",
      //   target: "Table",
      //   targetImportPath: "@/components/ui/table",
      //   complexity: "complex",
      //   guidelines: "1. DataTable is a fully featured table with sorting, pagination, filtering\n2. shadcn Table is headless — need to rebuild sorting/pagination logic\n3. Consider using @tanstack/react-table as the data layer\n4. Migrate column definitions to tanstack format",
      //   breakingChanges: [
      //     "Built-in sorting/filtering removed — must implement with @tanstack/react-table",
      //     "Pagination is now a separate component",
      //     "Column definitions format completely different",
      //   ],
      //   effort: "~4h per instance",
      // },
    ],
  },

  // ─── Dashboard ───────────────────────────────────────────
  dashboard: {
    title: "Design System Coverage",
    subtitle: "",
  },

  // ─── Output ──────────────────────────────────────────────
  output: {
    reportJson: "ds-coverage-report.json",
    dashboardHtml: "ds-coverage-dashboard.html",
  },
};
