/**
 * Template: Design System Compliance Skill
 *
 * Generates SKILL.md for Claude / Agents / Cursor skills.
 * References the generated rules and provides a quick summary.
 */

import type { DsCoverageConfig } from "../config.js";

export function generateSkill(config: DsCoverageConfig): string {
  const api = config.componentAnalysis.api;
  const primaryDir = config.componentAnalysis.primaryDirectory;

  const violationSummary = Object.entries(config.violations)
    .filter(([, v]) => v.enabled)
    .map(([, v]) => `${v.icon} ${v.label}`)
    .join(", ");

  const forbiddenSizesList = api.forbiddenSizes.length > 0
    ? api.forbiddenSizes.map((s) => `\`${s}\``).join(", ")
    : "";

  return `---
name: design-system-compliance
description: Design system compliance protocol. Covers token enforcement, component creation standards, Boy Scout Rule, and refactoring flagging conventions. Reference when building or modifying any frontend UI.
---

# Design System Compliance

> **Auto-generated by ds-coverage.** Re-run \`npx ds-coverage init\` to update.

**Load the rules:**
- \`.cursor/rules/design-system-compliance.md\` — Full compliance protocol
- \`.cursor/rules/ui-component-creation.md\` — Component creation standards

---

## Protocol summary

### CRITICAL — New code = design system only
**Every new line of UI code MUST use design system tokens and components. Zero tolerance for new hardcoded values.**

### Detected violations
The scanner checks for: ${violationSummary}

### Component decision hierarchy
1. **Use existing UI component** (\`${primaryDir}\`) — always check first
2. **Create new UI component** in \`${primaryDir}\` — CVA, semantic tokens, simple name
3. **Inline with tokens** — last resort, flag if pattern might repeat

### UI component API conventions
- Variant props: ${api.expectedProps.map((p) => `**\`${p}\`**`).join(", ")}
${api.expectedProps.includes("appearance") ? "- **`appearance`** (semantic meaning): `accent` (default), `danger`, `warning`, `success`, `info`" : ""}
${api.expectedProps.includes("hierarchy") ? "- **`hierarchy`** (visual weight): `primary`, `secondary` (default), `tertiary`" : ""}
${api.expectedProps.includes("size") ? `- **\`size\`** (full words): ${api.expectedSizes.map((s) => `\`${s}\``).join(", ")}` : ""}
- Always accept **\`className\`** for composition
${api.requireRadix ? "- Support **`asChild`** via Radix Slot" : ""}
- Use **\`compoundVariants\`** in CVA for appearance × hierarchy combinations
${api.forbiddenProps.length > 0 ? `- Forbidden legacy prop names: ${api.forbiddenProps.map((p) => `\`${p}\``).join(", ")}` : ""}
${forbiddenSizesList ? `- Forbidden legacy size values: ${forbiddenSizesList} — use full words instead` : ""}
- Zero hardcoded colors — semantic tokens only

### Boy Scout Rule
When editing any file in \`${config.scanDir}/\`:
1. **Apply simple token migrations** on code you touch — only when unambiguous
2. **Suggest options** for ambiguous cases — provide visual context when possible
3. Flag complex migrations with \`@ds-migrate: complex\`
4. Flag missing components with \`@ds-todo\`
5. Never break existing behavior

### Flagging conventions
\`\`\`tsx
// @ds-migrate: simple | Swap hardcoded value → semantic token
// @ds-migrate: complex | Description. Risks: ... Cost: ... Constraint: ...
// @ds-todo: Create <ComponentName> — rationale
\`\`\`

### Scanner
Run \`npx ds-coverage\` to generate a coverage report and interactive dashboard.
Run \`npx ds-coverage --open\` to open the dashboard in the browser immediately.
`;
}
